name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: check analora
        run: |
          python -c "import analora"

      - name: check analora.array
        run: |
          python -c "from analora import array"

      - name: check analora.content
        run: |
          python -c "from analora import content"

      - name: check analora.evaluator
        run: |
          python -c "from analora import evaluator"

      - name: check analora.ingestor
        run: |
          python -c "from analora import ingestor"
      - name: check analora.ingestor.polars
        run: |
          python -c "from analora.ingestor import polars"

      - name: check analora.metric
        run: |
          python -c "from analora import metric"

      - name: check analora.output
        run: |
          python -c "from analora import output"

      - name: check analora.plot
        run: |
          python -c "from analora import plot"

      - name: check analora.state
        run: |
          python -c "from analora import state"

      - name: check analora.testing
        run: |
          python -c "from analora import testing"

      - name: check analora.utils
        run: |
          python -c "from analora import utils"
